version: "3.5"
networks:
  localdev:
    name: localdev

services:
  main-api:
    build:
      context: ../src/
      dockerfile: Dockerfile
    volumes:
      - "../src/ProjectTemplate.Api:/app/ProjectTemplate.Api"
      - "../src/ProjectTemplate.Core:/app/ProjectTemplate.Core"
      - "../src/ProjectTemplate.Infrastructure:/app/ProjectTemplate.Infrastructure"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - SqlConnectionString=
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - pg-server
    networks:
      - localdev

  frontend:
    build:
      context: ../src/projecttemplate.frontend/
      dockerfile: Dockerfile
    volumes:
      - "../src/projecttemplate.frontend:/app/projecttemplate.frontend"
    ports:
      - "3000:3000"
    networks:
      - localdev
    environment: 
      - CHOKIDAR_USEPOLLING=true

  pg-server:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    container_name: pg-db-server
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/posgresql/data
    networks:
      - localdev

  pg-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-db-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - pg-server
    networks:
      - localdev
